language: python
python:
  - "3.6"
env:
  - MYCOLDMANAGER_KEY=travistest
addons:
  chrome: stable
install:
  - wget -N https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - PATH=$PATH:~/
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database mycoldmanager;'
script:
  - pytest
deploy:
  provider: heroku:HEROKU_MCM_GIT
  username: HEROKU_MAIL
  password: HEROKU_PASSWORD