# Generated by Django 3.1.3 on 2020-12-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustrialProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_product_name', models.CharField(max_length=100, unique=True)),
                ('ind_product_url', models.CharField(max_length=200, unique=True)),
                ('ind_product_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100, unique=True)),
                ('subcategory_peremption', models.IntegerField()),
                ('subcategory_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodapp.subcategory')),
            ],
        ),
    ]
