# Generated by Django 3.1.3 on 2020-11-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0002_product_user_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_product_name', models.CharField(max_length=100, unique=True)),
                ('ind_product_url', models.CharField(max_length=200, unique=True)),
                ('ind_product_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
