# Generated by Django 3.1.3 on 2020-12-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0003_unaccent'),
        ('prodapp', '0002_product_user_product'),
    ]

    operations = [
    ]
