# Generated by Django 3.1.3 on 2020-12-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodapp', '0006_auto_20201208_1044'),
        ('prodapp', '0004_merge_20201210_1259'),
    ]

    operations = [
    ]
