# Generated by Django 3.1.3 on 2020-12-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodapp', '0004_merge_20201203_1116'),
        ('colddeviceapp', '0002_colddevice_colddevice_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_add', models.DateField()),
                ('diary_modification', models.DateField(null=True)),
                ('diary_remove', models.DateField(null=True)),
                ('diary_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateField()),
                ('notification_is_send', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.IntegerField()),
                ('stock_compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colddeviceapp.compartment')),
                ('stock_diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.diary')),
                ('stock_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.notification')),
                ('stock_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodapp.product')),
            ],
        ),
    ]
