# Generated by Django 3.1.3 on 2020-11-16 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colddeviceapp', '0001_initial'),
        ('prodapp', '0002_product_user_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_number', models.IntegerField()),
                ('stock_compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colddeviceapp.compartment')),
                ('stock_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateField()),
                ('notification_is_send', models.IntegerField()),
                ('notification_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_add', models.DateField()),
                ('diary_modification', models.DateField()),
                ('diary_remove', models.DateField()),
                ('diary_number', models.IntegerField()),
                ('diary_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.stock')),
            ],
        ),
    ]
