# Generated by Django 3.1.3 on 2020-11-16 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colddevice_name', models.CharField(max_length=100)),
                ('colddevice_place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ColdDeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colddevicetype_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment_name', models.CharField(max_length=100)),
                ('compartment_colddevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colddeviceapp.colddevice')),
            ],
        ),
        migrations.AddField(
            model_name='colddevice',
            name='colddevice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colddeviceapp.colddevicetype'),
        ),
        migrations.AddField(
            model_name='colddevice',
            name='colddevice_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
